services:
  portfolio-service-backend-database:
    image: postgres:17-alpine
    restart: always
    container_name: portfolio-service-backend-database
    ports:
      - "${POSTGRES_HOST_PORT:-7401}:5432"
    env_file:
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  portfolio-service-backend:
    build: .
    container_name: portfolio-service-backend
    restart: always
    ports:
      - "2390:${PORT-3000}"
    env_file:
      - .env
    depends_on:
      - portfolio-service-backend-database
