services:
  portfolio-service-backend-database:
    image: postgres:17-alpine
    restart: always
    container_name: portfolio-service-backend-database
    ports:
      - "${POSTGRES_HOST_PORT:-7401}:5432"
    env_file:
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-service-network
  portfolio-service-backend:
    build: .
    container_name: portfolio-service-backend
    restart: always
    ports:
      - "2390:${PORT-3000}"
    env_file:
      - .env
    depends_on:
      portfolio-service-backend-database:
        condition: service_healthy
    networks:
      - portfolio-service-network
networks:
  portfolio-service-network:
    driver: bridge
