services:
  portfolio-service-backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.main
      args:
        - NODE_VERSION=${NODE_VERSION:-24-alpine}
        - PORT=${PORT:-3000}
    container_name: portfolio-service-backend
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    depends_on:
      - portfolio-service-backend-database
    networks:
      - portfolio-service-network
      - crypto-bff-network

  portfolio-service-backend-database:
    image: postgres:17-alpine
    restart: always
    container_name: portfolio-service-backend-database
    ports:
      - "${POSTGRES_HOST_PORT:-7401}:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - portfolio-service-network

volumes:
  pg_data:

networks:
  portfolio-service-network:
  crypto-bff-network:
    external: true
